language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - "12"

matrix:
  allow_failures:
  - os: windows

git:
  depth: 1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y strawberryperl && export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"; fi

install:
  - npm ci

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == "10" ]]; then npm run binary:pack && npm run binary:publish; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_NODE_VERSION" == "12" ]]; then TARGET_ARCH=arm npm run cross && TARGET_ARCH=arm npm run binary:publish; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_NODE_VERSION" == "12" ]]; then TARGET_ARCH=arm64 npm run cross && TARGET_ARCH=arm64 npm run binary:publish; fi

cache: npm

script:
  - npm run test
